[project]
name = "benzene"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Manabendu-ai", email = "rikugithub@gmail.com" }
]
requires-python = ">=3.12.11"
dependencies = []

[project.scripts]
benzene = "benzene:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
